### ISSUE TITLE
Add a README file

### ISSUE THREAD

**Issue by dhanvi** [ctfs/write-ups-2013#1]
@YASME-Tim can you add some file to this this repo as an empty repo can't be cloned or forked :-1: 

hope you change the README file and contributing.md 

for example say that the the writeup's for the year 20xx will be under ctfs/20xx

and wish we have can have a repo for the war games or some ctf's which will be online for ever but we should not give the flags of such competition

hope we can do this @mathiasbynens

**Comment by abpolym** [comment]
@dhanvi I'll do that in the next 24h. I don't know what you mean with the third sentence. Also we both have added pico, an online-forever CTF, just recently - so we just add the ctfs to the write-ups-20xx directories, instead of creating another repo for that type of CTF. Not giving away the flag for these types of CTF is noted and considered.

**Comment by abpolym** [comment]
Done. Also it is always forkable, even if it's an empty repo. Just do `git clone https://github.com/ctfs/write-ups-2013.git`

**Comment by dhanvi** [comment]
what I meant was that we can create a repo for war games or ctf's that doesn't have a year associated with them like under 
ctfs/war-games for http://overthewire.org/wargames/ not sure if the owner accepts this one or we can create a new organisation for this one like github.com/war-games :+1:   

ctfs/for-ever      (or something relevant for ctf's which doesn't have a year associated with them) but we should not revel the flag as it gives a unfair advantage :-1: to every one for example this ctf http://ctf.hackevergreen.org/

**Comment by mathiasbynens** [comment]
There should be a `write-ups-` prefix at the very least.

I’d go with `write-ups-evergreen`.
